### ISSUE TITLE
Advanced Schedule 

### ISSUE THREAD

**Issue by rickyyx** [githubxxcc/pintos#2]
## TODO: 
- [x] init a thread with correct recent_cpu
- [x] init with correct load 
- [x] init thread with correct priority
- [x] calcualte_priority

### Data structure for the MLFQ
 - [NUM_PRI] queues? 
-> array of lists? 
-> a rq_status 64 bits number. 

### For thread_tick(): 
- At each second: 
update_load_avg()
update_all_recent_cpu()
- At each tick: update_cur_recent_cpu(): increment by one for current (non-idle) running thread
- At 4th tick : update_priority() (doing it first to take into account the newly created one?) 

- Yield if necessary? 

### For thread_next_to_run(): 
- [x] choose the highest queue and get the first guy.
